### ISSUE TITLE
PlayerDeathEvent don’t work

### ISSUE THREAD

**Issue by Buvance** [Imanity-Software/ImanitySpigot3-git#85] opened 2022-01-09 09:25 UTC
### Expected behavior

The PlayerDeathEvent doesn't have a bug in itself but apparently all just doesn't work, it tries to change the death message: it doesn't change anything

### Observed/Actual behavior

The PlayerDeathEvent doesn't have a bug in itself but apparently all just doesn't work, it tries to change the death message: it doesn't change anything

### Steps/models to reproduce

On sysout on event return anything

### Plugin list

One of mine

### ImanitySpigot3 version

The last

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by Whizyyy** [comment] 2022-01-09 11:21
Hello,
First, if you want your issues to be solved correctly, please fill the issues correctly. "The last" is not a valid version, "Expected Behavior" and "Observed Behavior" are not supposed to be the same thing.

But I think I understand your problem, are you sure that the "showDeathMessages" gamerule is enabled?

**Comment by Buvance** [comment] 2022-01-09 11:27
For the version is : 2021.12.1 BUILD 2
But i make a SysOUT on e.getENtity().getKiller() and return any message

**Comment by Whizyyy** [comment] 2022-01-09 11:33
I just tested myself and the event is working perfectly. Have you read documentation about this event? PlayerDeathEvent#getEntity#getKiller can return a null value in some cases and using a "SysOUT" with a null value print nothing.

**Comment by Buvance** [comment] 2022-01-09 11:34
But me i say in the version 2 it's working, i've updated to the three its not working...

**Comment by Whizyyy** [comment] 2022-01-09 11:36
Well, what is not working?? Please provide more information: code screen, video of the problem... and be sure to have verified the things I said above.

**Comment by Whizyyy** [comment] 2022-01-09 12:17
Issue fixed in ticket. The problem was caused by a wrong usage of the Bukkit API. No issue with PlayerDeathEvent

**Closed by Whizyyy** 2022-01-09 12:17 UTC
Labels: resolution:by-plugin
