### ISSUE TITLE
Copy item bug

### ISSUE THREAD

**Issue by xpghard** [Imanity-Software/ImanitySpigot3-git#88] opened 2022-01-29 23:09 UTC
### Expected behavior

not copying items

### Observed/Actual behavior

When it explodes, it is not like on clean paper and copies the blocks

### Steps/models to reproduce

https://youtu.be/dzKFXwGeQlo

### Plugin list

LuckPerms

### ImanitySpigot3 version

2022.01.1 BUILD 1

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by xpghard** [comment] 2022-01-29 23:17
![image](https://user-images.githubusercontent.com/46456820/151680667-20e3521c-050d-46b2-993d-7a3472edb40f.png)

**Comment by Whizyyy** [comment] 2022-02-23 16:54
Hello, we was not able to reproduce your issue, can you provide your configuration? Including imanity files and also server files (server.properties, spigot.yml)

**Comment by xpghard** [comment] 2022-03-08 20:10
I download newest rancha(2021.11.1 LTS BUILD 4) and chose spigotJarVersion: 2022.01.1 BUILD 3
config and all is default i download rancha and run clear server without plugins.
But is working only when you spawn 100+ minecart.
How it's working? Every explosion of minecart looping nears blocks and drops it. Problem is loops working on block which previous explosion in same time broke. I appeal to repair this bug because player can copy difficulty to have items.

**Comment by Whizyyy** [comment] 2022-04-22 07:57
Hello, please test with the latest version. The issue should be fixed.

**Closed by Whizyyy** 2022-04-22 07:57 UTC
Labels: cannot reproduce
